name: starcore_balance_server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  xml: ^5.1.0
  logging: ^1.0.1
  pretty_json:
#  path: ^1.7.0

dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: ^1.0.0
  pedantic: ^1.9.0
